"""Initial migration

Revision ID: b1e716bc211b
Revises: 
Create Date: 2024-05-15 00:57:35.963778

"""
from alembic import op
import sqlalchemy as sa
import hashlib
from models import Users

user = Users()

# revision identifiers, used by Alembic.
revision = 'b1e716bc211b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_category', name=op.f('pk_category'))
    )
    op.create_table('publishing',
    sa.Column('id_publishing', sa.Integer(), nullable=False),
    sa.Column('name_publishing', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_publishing', name=op.f('pk_publishing'))
    )
    op.create_table('roles',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_role', name=op.f('pk_roles'))
    )
    op.create_table('series',
    sa.Column('id_series', sa.Integer(), nullable=False),
    sa.Column('series_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_series', name=op.f('pk_series'))
    )
    op.create_table('books',
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=128), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('id_series', sa.Integer(), nullable=True),
    sa.Column('id_publishing', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['category.id_category'], name=op.f('fk_books_id_category_category')),
    sa.ForeignKeyConstraint(['id_publishing'], ['publishing.id_publishing'], name=op.f('fk_books_id_publishing_publishing')),
    sa.ForeignKeyConstraint(['id_series'], ['series.id_series'], name=op.f('fk_books_id_series_series')),
    sa.PrimaryKeyConstraint('id_book', name=op.f('pk_books'))
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(length=128), nullable=False),
    sa.Column('login', sa.String(length=32), nullable=False),
    sa.Column('hash_pass', sa.String(length=256), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id_role'], name=op.f('fk_users_id_role_roles')),
    sa.PrimaryKeyConstraint('id_user', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('rent',
    sa.Column('id_rent', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['books.id_book'], name=op.f('fk_rent_id_book_books')),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], name=op.f('fk_rent_id_user_users')),
    sa.PrimaryKeyConstraint('id_rent', name=op.f('pk_rent'))
    )
    # ### end Alembic commands ###
    data_upgrades()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rent')
    op.drop_table('users')
    op.drop_table('books')
    op.drop_table('series')
    op.drop_table('roles')
    op.drop_table('publishing')
    op.drop_table('category')
    # ### end Alembic commands ###

def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

def data_upgrades():

    category_table = sa.table('category',
                              sa.column('category_name', sa.String))
    publishing_table = sa.table('publishing',
                                sa.column('name_publishing', sa.String))
    roles_table = sa.table('roles',
                           sa.column('role_name', sa.String))
    series_table = sa.table('series',
                            sa.column('series_name', sa.String))
    books_table = sa.table('books',
                           sa.column('book_name', sa.String),
                           sa.column('author', sa.String),
                           sa.column('id_category', sa.Integer),
                           sa.column('id_series', sa.Integer),
                           sa.column('id_publishing', sa.Integer))
    users_table = sa.table('users',
                           sa.column('fio', sa.String),
                           sa.column('login', sa.String),
                           sa.column('hash_pass', sa.String),
                           sa.column('id_role', sa.Integer))

    op.bulk_insert(category_table,
        [
            {'id_category': 1, 'category_name': 'Фантастика'},
            {'id_category': 2, 'category_name': 'Фэнтези'},
            {'id_category': 3, 'category_name': 'Детективы'},
            {'id_category': 4, 'category_name': 'Романы'},
            {'id_category': 5, 'category_name': 'Исторические'},
            {'id_category': 6, 'category_name': 'Биографии и мемуары'},
            {'id_category': 7, 'category_name': 'Научная литература'},
            {'id_category': 8, 'category_name': 'Саморазвитие и мотивация'},
            {'id_category': 9, 'category_name': 'Психология'},
            {'id_category': 10, 'category_name': 'Приключения'},
            {'id_category': 11, 'category_name': 'Ужасы и мистика'},
            {'id_category': 12, 'category_name': 'Кулинарные книги'},
            {'id_category': 13, 'category_name': 'Искусство и культура'},
            {'id_category': 14, 'category_name': 'Поэзия и драматургия'},
            {'id_category': 15, 'category_name': 'Детская литература'},
        ])
    op.bulk_insert(publishing_table, 
        [
            {'id_publishing': 1, 'name_publishing': 'Литературный ветер'},
            {'id_publishing': 2, 'name_publishing': 'Солнечная стрела'},
            {'id_publishing': 3, 'name_publishing': 'Звездная поляна'},
            {'id_publishing': 4, 'name_publishing': 'Тихий шелест'},
            {'id_publishing': 5, 'name_publishing': 'Золотое перо'},
            {'id_publishing': 6, 'name_publishing': 'Вечерние огни'},
            {'id_publishing': 7, 'name_publishing': 'Серебрянный Лист'},
            {'id_publishing': 8, 'name_publishing': 'Небесная книга'},
            {'id_publishing': 9, 'name_publishing': 'Лесные сказки'},
            {'id_publishing': 10, 'name_publishing': 'Морские глубины'},
        ])
    op.bulk_insert(roles_table, 
        [
            {'id_role': 1, 'role_name': 'Администратор'},
            {'id_role': 2, 'role_name': 'Библиотекарь'},
            {'id_role': 3, 'role_name': 'Читатель'},
        ])
    op.bulk_insert(series_table,
        [
            {'id_series': 1, 'series_name': 'Тайны Вселенной'},
            {'id_series': 2, 'series_name': 'Эпопея героя'},
            {'id_series': 3, 'series_name': 'Легенды древних королевств'},
            {'id_series': 4, 'series_name': 'Волшебные грани реальности'},
            {'id_series': 5, 'series_name': 'Мистические оды'},
        ])
    op.bulk_insert(books_table,
        [
            {'id_book': 1, 'book_name': 'Первому игроку приготовиться', 'author': 'Эрнест Клайн', 'id_category': 1, 'id_series': 4, 'id_publishing': 1},
            {'id_book': 2, 'book_name': 'Автостопом по галактике', 'author': 'Дуглас Адамс', 'id_category': 1, 'id_series': 4, 'id_publishing': 5},
            {'id_book': 3, 'book_name': 'Пламя и кровь', 'author': 'Джордж Мартин', 'id_category': 2, 'id_series': 4, 'id_publishing': 4},
            {'id_book': 4, 'book_name': 'Танец с драконами', 'author': 'Джордж Мартин', 'id_category': 2, 'id_series': 4, 'id_publishing': 3},
            {'id_book': 5, 'book_name': 'Этюд в багровых тонах', 'author': 'Артур Конан Дойл', 'id_category': 3, 'id_series': 2, 'id_publishing': 9},
            {'id_book': 6, 'book_name': 'Собака Баскервилей', 'author': 'Артур Конан Дойл', 'id_category': 3, 'id_series': 2, 'id_publishing': 10},
            {'id_book': 7, 'book_name': 'Мы', 'author': 'Е. И. Замятин', 'id_category': 4, 'id_series': 2, 'id_publishing': 2},
            {'id_book': 8, 'book_name': 'Мастер и Маргарита', 'author': 'М. А. Булгаков', 'id_category': 4, 'id_series': 2, 'id_publishing': 6},
            {'id_book': 9, 'book_name': 'Железный король', 'author': 'Морис Дрюон', 'id_category': 5, 'id_series': 3, 'id_publishing': 8},
            {'id_book': 10, 'book_name': 'Чингисхан', 'author': 'В. Г. Ян', 'id_category': 5, 'id_series': 3, 'id_publishing': 7},
            {'id_book': 11, 'book_name': 'Жажда жизни', 'author': 'Ирвинг Стоун', 'id_category': 6, 'id_series': None,'id_publishing': 10},
            {'id_book': 12, 'book_name': 'Почти серьезно', 'author': 'Юрий Никулин', 'id_category': 6, 'id_series': None, 'id_publishing': 2},
            {'id_book': 13, 'book_name': 'Краткая история времени', 'author': 'Стивен Хокинг', 'id_category': 7, 'id_series': 1, 'id_publishing': 5},
            {'id_book': 14, 'book_name': 'Теория всего', 'author': 'Стивен Хокинг', 'id_category': 7, 'id_series': 1, 'id_publishing': 1},
            {'id_book': 15, 'book_name': 'Важные годы. Почему не стоит откладывать жизнь на потом', 'author': 'Мэг Джей', 'id_category': 8, 'id_series': None, 'id_publishing': 6},
            {'id_book': 16, 'book_name': 'НИ СЫ. Иди вперед и ничего не бойся', 'author': 'Джен Синсеро', 'id_category': 8, 'id_series': None, 'id_publishing': 7},
            {'id_book': 17, 'book_name': 'Чертоги разума', 'author': 'Андрей Курпатов', 'id_category': 9, 'id_series': None, 'id_publishing': 3},
            {'id_book': 18, 'book_name': 'Свобода от тревоги. Справиться с тревогой, пока она не расправилась с тобой', 'author': 'Роберт Лихи', 'id_category': 9, 'id_series': None, 'id_publishing': 9},
            {'id_book': 19, 'book_name': 'Таинственный остров', 'author': 'Жюль Верн', 'id_category': 10, 'id_series': 2, 'id_publishing': 4},
            {'id_book': 20, 'book_name': 'Зов предков', 'author': 'Джек Лондон', 'id_category': 10, 'id_series': 2, 'id_publishing': 8},
            {'id_book': 21, 'book_name': 'Сияние', 'author': 'Стивен Кинг', 'id_category': 11, 'id_series': 5, 'id_publishing': 4},
            {'id_book': 22, 'book_name': 'Кладбище домашних животных', 'author': 'Стивен Кинг', 'id_category': 11, 'id_series': 5, 'id_publishing': 8},
            {'id_book': 23, 'book_name': 'Абсент', 'author': 'Фил Бейкер', 'id_category': 12, 'id_series': None, 'id_publishing': 5},
            {'id_book': 24, 'book_name': 'Вино. Практический путеводитель', 'author': 'Джастин Хэммек', 'id_category': 12, 'id_series': None, 'id_publishing': 2},
            {'id_book': 25, 'book_name': 'Искусство видеть', 'author': 'Джон Бергер', 'id_category': 13, 'id_series': None, 'id_publishing': 1},
            {'id_book': 26, 'book_name': 'Япония. Введение в искусство и кульутуру', 'author': 'Анна Пушакова', 'id_category': 13, 'id_series': None, 'id_publishing': 3},
            {'id_book': 27, 'book_name': 'Комедии', 'author': 'Уильям Шекспир', 'id_category': 14, 'id_series': None, 'id_publishing': 6},
            {'id_book': 28, 'book_name': 'Трагедии', 'author': 'Софокл', 'id_category': 14, 'id_series': None, 'id_publishing': 10},
            {'id_book': 29, 'book_name': 'Ёжик в тумане', 'author': 'С. С. Козлов', 'id_category': 15, 'id_series': None, 'id_publishing': 7},
            {'id_book': 30, 'book_name': 'Пеппи Длинныйчулок', 'author': 'Астрид Линдгрен', 'id_category': 15, 'id_series': None, 'id_publishing': 9},

        ])
    op.bulk_insert(users_table, 
        [
            {'id_user': 1, 'fio': 'Крылов Даниил Александрович', 'login': 'admin', 'hash_pass': user.set_password('admin123'), 'id_role': 1},
            {'id_user': 2, 'fio': 'Осипова Мария Арсентьевна', 'login': 'librarian1', 'hash_pass': user.set_password('librarian1'), 'id_role': 2},
            {'id_user': 3, 'fio': 'Дмитриева Алина Тимофеевна', 'login': 'librarian2', 'hash_pass': user.set_password('librarian2'), 'id_role': 2},
            {'id_user': 4, 'fio': 'Федотов Владимир Даниилович', 'login': 'FedotovVD', 'hash_pass': user.set_password('reader1'), 'id_role': 3},
            {'id_user': 5, 'fio': 'Щербаков Данила Иванович', 'login': 'ShcherDI', 'hash_pass': user.set_password('reader2'), 'id_role': 3},
        ])
    